steps:
- name: "gcr.io/cloud-builders/docker"
  args: [ 'build', '-t', 'gcr.io/qwiklabs-gcp-02-2d3688bf7c1c/gcpdevops', '.']

- name: "gcr.io/cloud-builders/docker"
  args: [ "push", "gcr.io/qwiklabs-gcp-02-2d3688bf7c1c/gcpdevops"]

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/qwiklabs-gcp-02-2d3688bf7c1c/gcpdevops
  - --location=us-central1-c
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod