apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template: 
    metadata: 
      labels:
        app: gcp
    spec: 
      containers:
      - name: gcp-devops-gke
        image: gcr.io/qwiklabs-gcp-02-2d3688bf7c1c/gcpdevops        
        ports:
        - containerPort: 5000
        env:
          - name: PORT 
            value: "5000"

--- 
apiVersion: v1 
kind: Service
metadata:
  name: gcp-devops-gke
spec:
  selector: 
    app: gcp
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer